# Options for analysis running.
run:
  timeout: 10m
  concurrency: 4

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asciicheck
    - bodyclose
    - dogsled
    - exhaustive
    - gocognit
    - gofmt
    - goheader
    - goimports
    - gosec
    - misspell
    - nakedret
    - nestif
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace
    - gocyclo

linters-settings:
  staticcheck:
    checks: ["all"]
  funlen:
    lines: -1
    statements: -1
  gosec:
    excludes:
      - G601
      - G304
      - G101
